InterpolSearch.out: InterpolSearch.c
	gcc -o InterpolSearch.out InterpolSearch.c
SelectionSort.out: SelectionSort.c
	gcc -o SelectionSort.out SelectionSort.c
insertSort.out: insertSort.c
	gcc -o insertSort.out insertSort.c
MergeSort.out: MergeSort.c
	gcc -o MergeSort.out MergeSort.c
QuickSort.out: QuickSort.c
	gcc -o QuickSort.out QuickSort.c
clean:
	rm -rf *.o
	rm -rf *.gch
	rm -rf *.out