BubbleSort.out: BubbleSort.c
	gcc -o BubbleSort.out BubbleSort.c
SelectionSort.out: SelectionSort.c
	gcc -o SelectionSort.out SelectionSort.c
insertSort.out: insertSort.c
	gcc -o insertSort.out insertSort.c

clean:
	rm -rf *.o
	rm -rf *.gch
	rm -rf *.out