name: frontdoor-1

services:
  proxy:
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - backend

  backend:
    build: backend
    expose:
      - 3000
    volumes:
      - ./flag:/app/flag:ro
    environment:
      BACKEND_HOST: "0.0.0.0"
      BACKEND_PORT: 3000
      GUEST_ID: "guest"
      GUEST_PWD: "guest"
